/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AttachmentUpdateVersion model module.
* @module model/AttachmentUpdateVersion
* @version 1.0.0
*/
export default class AttachmentUpdateVersion {
    /**
    * Constructs a new <code>AttachmentUpdateVersion</code>.
    * The attachment version. Set this to the current version number of the attachment. Note, the version number only needs to be incremented when updating the actual attachment, not its properties.
    * @alias module:model/AttachmentUpdateVersion
    * @class
    * @param _number {Number} The version number.
    */

    constructor(_number) {
        
        
        this['number'] = _number;
        
    }

    /**
    * Constructs a <code>AttachmentUpdateVersion</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AttachmentUpdateVersion} obj Optional instance to populate.
    * @return {module:model/AttachmentUpdateVersion} The populated <code>AttachmentUpdateVersion</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttachmentUpdateVersion();
                        
            
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The version number.
    * @member {Number} number
    */
    number = undefined;




}
