/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContentBodyCreate from './ContentBodyCreate';
import ContentTemplateCreateSpace from './ContentTemplateCreateSpace';
import Label from './Label';

/**
* The ContentTemplateCreate model module.
* @module model/ContentTemplateCreate
* @version 1.0.0
*/
export default class ContentTemplateCreate {
    /**
    * Constructs a new <code>ContentTemplateCreate</code>.
    * This object is used to create content templates.
    * @alias module:model/ContentTemplateCreate
    * @class
    * @param name {String} The name of the new template.
    * @param templateType {String} The type of the new template. Set to `page`.
    * @param body {module:model/ContentBodyCreate} 
    */

    constructor(name, templateType, body) {
        
        
        this['name'] = name;
        this['templateType'] = templateType;
        this['body'] = body;
        
    }

    /**
    * Constructs a <code>ContentTemplateCreate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentTemplateCreate} obj Optional instance to populate.
    * @return {module:model/ContentTemplateCreate} The populated <code>ContentTemplateCreate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentTemplateCreate();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('templateType')) {
                obj['templateType'] = ApiClient.convertToType(data['templateType'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ContentBodyCreate.constructFromObject(data['body']);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], [Label]);
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ContentTemplateCreateSpace.constructFromObject(data['space']);
            }
        }
        return obj;
    }

    /**
    * The name of the new template.
    * @member {String} name
    */
    name = undefined;
    /**
    * The type of the new template. Set to `page`.
    * @member {String} templateType
    */
    templateType = undefined;
    /**
    * @member {module:model/ContentBodyCreate} body
    */
    body = undefined;
    /**
    * A description of the new template.
    * @member {String} description
    */
    description = undefined;
    /**
    * Labels for the new template.
    * @member {Array.<module:model/Label>} labels
    */
    labels = undefined;
    /**
    * @member {module:model/ContentTemplateCreateSpace} space
    */
    space = undefined;




}
