/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Container from './Container';
import Content from './Content';
import ContentAttachmentExtensions from './ContentAttachmentExtensions';
import ContentAttachmentMetadata from './ContentAttachmentMetadata';
import ContentBody from './ContentBody';
import ContentChildType from './ContentChildType';
import ContentChildren from './ContentChildren';
import ContentExpandable from './ContentExpandable';
import ContentHistory from './ContentHistory';
import ContentRestrictions from './ContentRestrictions';
import GenericLinks from './GenericLinks';
import OperationCheckResult from './OperationCheckResult';
import Space from './Space';
import Version from './Version';

/**
* The ContentAttachment model module.
* @module model/ContentAttachment
* @version 1.0.0
*/
export default class ContentAttachment {
    /**
    * Constructs a new <code>ContentAttachment</code>.
    * Representation of an attachment (content)
    * @alias module:model/ContentAttachment
    * @class
    * @extends module:model/Content
    * @param id {} 
    * @param type {} 
    * @param status {} 
    * @param title {} 
    * @param expandable {} 
    * @param links {} 
    * @param metadata {} 
    * @param extensions {} 
    */

    constructor(id, type, status, title, expandable, links, metadata, extensions) {
        Content.call(this);
        
        this['metadata'] = metadata;
        this['extensions'] = extensions;
        this['_links'] = links;
        
    }

    /**
    * Constructs a <code>ContentAttachment</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentAttachment} obj Optional instance to populate.
    * @return {module:model/ContentAttachment} The populated <code>ContentAttachment</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentAttachment();
            
            Content.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ContentAttachmentMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('extensions')) {
                obj['extensions'] = ContentAttachmentExtensions.constructFromObject(data['extensions']);
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = GenericLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ContentAttachmentMetadata} metadata
    */
    metadata = undefined;
    /**
    * @member {module:model/ContentAttachmentExtensions} extensions
    */
    extensions = undefined;
    /**
    * @member {module:model/GenericLinks} _links
    */
    _links = undefined;




}
