/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContentBodyCreate from './ContentBodyCreate';

/**
* The ContentCreateBody model module.
* @module model/ContentCreateBody
* @version 1.0.0
*/
export default class ContentCreateBody {
    /**
    * Constructs a new <code>ContentCreateBody</code>.
    * The body of the new content. Does not apply to attachments. Only one body format should be specified as the property for this object, e.g. &#x60;storage&#x60;.  Note, &#x60;editor2&#x60; format is used by Atlassian only. &#x60;anonymous_export_view&#x60; is the same as &#x27;export_view&#x27; format but only content viewable by an anonymous user is included.
    * @alias module:model/ContentCreateBody
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ContentCreateBody</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentCreateBody} obj Optional instance to populate.
    * @return {module:model/ContentCreateBody} The populated <code>ContentCreateBody</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentCreateBody();
                        
            
            if (data.hasOwnProperty('view')) {
                obj['view'] = ContentBodyCreate.constructFromObject(data['view']);
            }
            if (data.hasOwnProperty('export_view')) {
                obj['export_view'] = ContentBodyCreate.constructFromObject(data['export_view']);
            }
            if (data.hasOwnProperty('styled_view')) {
                obj['styled_view'] = ContentBodyCreate.constructFromObject(data['styled_view']);
            }
            if (data.hasOwnProperty('storage')) {
                obj['storage'] = ContentBodyCreate.constructFromObject(data['storage']);
            }
            if (data.hasOwnProperty('editor2')) {
                obj['editor2'] = ContentBodyCreate.constructFromObject(data['editor2']);
            }
            if (data.hasOwnProperty('anonymous_export_view')) {
                obj['anonymous_export_view'] = ContentBodyCreate.constructFromObject(data['anonymous_export_view']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ContentBodyCreate} view
    */
    view = undefined;
    /**
    * @member {module:model/ContentBodyCreate} export_view
    */
    export_view = undefined;
    /**
    * @member {module:model/ContentBodyCreate} styled_view
    */
    styled_view = undefined;
    /**
    * @member {module:model/ContentBodyCreate} storage
    */
    storage = undefined;
    /**
    * @member {module:model/ContentBodyCreate} editor2
    */
    editor2 = undefined;
    /**
    * @member {module:model/ContentBodyCreate} anonymous_export_view
    */
    anonymous_export_view = undefined;




}
