/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContentBlueprintDraftAncestors from './ContentBlueprintDraftAncestors';
import ContentBlueprintDraftSpace from './ContentBlueprintDraftSpace';
import ContentBlueprintDraftVersion from './ContentBlueprintDraftVersion';

/**
* The ContentBlueprintDraft model module.
* @module model/ContentBlueprintDraft
* @version 1.0.0
*/
export default class ContentBlueprintDraft {
    /**
    * Constructs a new <code>ContentBlueprintDraft</code>.
    * @alias module:model/ContentBlueprintDraft
    * @class
    * @param version {module:model/ContentBlueprintDraftVersion} 
    * @param title {String} The title of the content. If you don't want to change the title, set this to the current title of the draft.
    * @param type {module:model/ContentBlueprintDraft.TypeEnum} The type of content. Set this to `page`.
    */

    constructor(version, title, type) {
        
        
        this['version'] = version;
        this['title'] = title;
        this['type'] = type;
        
    }

    /**
    * Constructs a <code>ContentBlueprintDraft</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContentBlueprintDraft} obj Optional instance to populate.
    * @return {module:model/ContentBlueprintDraft} The populated <code>ContentBlueprintDraft</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContentBlueprintDraft();
                        
            
            if (data.hasOwnProperty('version')) {
                obj['version'] = ContentBlueprintDraftVersion.constructFromObject(data['version']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('space')) {
                obj['space'] = ContentBlueprintDraftSpace.constructFromObject(data['space']);
            }
            if (data.hasOwnProperty('ancestors')) {
                obj['ancestors'] = ApiClient.convertToType(data['ancestors'], [ContentBlueprintDraftAncestors]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ContentBlueprintDraftVersion} version
    */
    version = undefined;
    /**
    * The title of the content. If you don't want to change the title, set this to the current title of the draft.
    * @member {String} title
    */
    title = undefined;
    /**
    * The type of content. Set this to `page`.
    * @member {module:model/ContentBlueprintDraft.TypeEnum} type
    */
    type = undefined;
    /**
    * The status of the content. Set this to `current` or omit it altogether.
    * @member {module:model/ContentBlueprintDraft.StatusEnum} status
    * @default 'current'
    */
    status = 'current';
    /**
    * @member {module:model/ContentBlueprintDraftSpace} space
    */
    space = undefined;
    /**
    * The new ancestor (i.e. parent page) for the content. If you have specified an ancestor, you must also specify a `space` property in the request body for the space that the ancestor is in.  Note, if you specify more than one ancestor, the last ID in the array will be selected as the parent page for the content.
    * @member {Array.<module:model/ContentBlueprintDraftAncestors>} ancestors
    */
    ancestors = undefined;



    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
        /**
         * value: "page"
         * @const
         */
        "page": "page"    };
    /**
    * Allowed values for the <code>status</code> property.
    * @enum {String}
    * @readonly
    */
    static StatusEnum = {
        /**
         * value: "current"
         * @const
         */
        "current": "current"    };

}
