/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GenericLinks from './GenericLinks';
import SpacePermissionV2Operation from './SpacePermissionV2Operation';
import SpacePermissionV2Subject from './SpacePermissionV2Subject';

/**
* The SpacePermissionV2 model module.
* @module model/SpacePermissionV2
* @version 1.0.0
*/
export default class SpacePermissionV2 {
    /**
    * Constructs a new <code>SpacePermissionV2</code>.
    * This object represents a single space permission. Permissions consist of at least one operation object with an accompanying subjects object.  The following combinations of &#x60;operation.type&#x60; and &#x60;operation.target&#x60; values are valid for the &#x60;operation&#x60; object:    - &#x27;create&#x27;: &#x27;page&#x27;, &#x27;blogpost&#x27;, &#x27;comment&#x27;, &#x27;attachment&#x27;   - &#x27;read&#x27;: &#x27;space&#x27;   - &#x27;delete&#x27;: &#x27;page&#x27;, &#x27;blogpost&#x27;, &#x27;comment&#x27;, &#x27;attachment&#x27;   - &#x27;export&#x27;: &#x27;space&#x27;   - &#x27;administer&#x27;: &#x27;space&#x27;
    * @alias module:model/SpacePermissionV2
    * @class
    * @param subject {module:model/SpacePermissionV2Subject} 
    * @param operation {module:model/SpacePermissionV2Operation} 
    */

    constructor(subject, operation) {
        
        
        this['subject'] = subject;
        this['operation'] = operation;
        
    }

    /**
    * Constructs a <code>SpacePermissionV2</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SpacePermissionV2} obj Optional instance to populate.
    * @return {module:model/SpacePermissionV2} The populated <code>SpacePermissionV2</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpacePermissionV2();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = SpacePermissionV2Subject.constructFromObject(data['subject']);
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = SpacePermissionV2Operation.constructFromObject(data['operation']);
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = GenericLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {module:model/SpacePermissionV2Subject} subject
    */
    subject = undefined;
    /**
    * @member {module:model/SpacePermissionV2Operation} operation
    */
    operation = undefined;
    /**
    * @member {module:model/GenericLinks} _links
    */
    _links = undefined;




}
