/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Content from './Content';
import GenericLinks from './GenericLinks';
import User from './User';
import UsersUserKeys from './UsersUserKeys';
import VersionExpandable from './VersionExpandable';

/**
* The Version model module.
* @module model/Version
* @version 1.0.0
*/
export default class Version {
    /**
    * Constructs a new <code>Version</code>.
    * @alias module:model/Version
    * @class
    * @param by {module:model/User} 
    * @param when {Date} 
    * @param friendlyWhen {String} 
    * @param message {String} 
    * @param _number {Number} 
    * @param minorEdit {Boolean} 
    * @param expandable {module:model/VersionExpandable} 
    * @param links {module:model/GenericLinks} 
    */

    constructor(by, when, friendlyWhen, message, _number, minorEdit, expandable, links) {
        
        
        this['by'] = by;
        this['when'] = when;
        this['friendlyWhen'] = friendlyWhen;
        this['message'] = message;
        this['number'] = _number;
        this['minorEdit'] = minorEdit;
        this['_expandable'] = expandable;
        this['_links'] = links;
        
    }

    /**
    * Constructs a <code>Version</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Version} obj Optional instance to populate.
    * @return {module:model/Version} The populated <code>Version</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Version();
                        
            
            if (data.hasOwnProperty('by')) {
                obj['by'] = User.constructFromObject(data['by']);
            }
            if (data.hasOwnProperty('when')) {
                obj['when'] = ApiClient.convertToType(data['when'], 'Date');
            }
            if (data.hasOwnProperty('friendlyWhen')) {
                obj['friendlyWhen'] = ApiClient.convertToType(data['friendlyWhen'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('minorEdit')) {
                obj['minorEdit'] = ApiClient.convertToType(data['minorEdit'], 'Boolean');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = Content.constructFromObject(data['content']);
            }
            if (data.hasOwnProperty('collaborators')) {
                obj['collaborators'] = UsersUserKeys.constructFromObject(data['collaborators']);
            }
            if (data.hasOwnProperty('_expandable')) {
                obj['_expandable'] = VersionExpandable.constructFromObject(data['_expandable']);
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = GenericLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/User} by
    */
    by = undefined;
    /**
    * @member {Date} when
    */
    when = undefined;
    /**
    * @member {String} friendlyWhen
    */
    friendlyWhen = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {Number} number
    */
    number = undefined;
    /**
    * @member {Boolean} minorEdit
    */
    minorEdit = undefined;
    /**
    * @member {module:model/Content} content
    */
    content = undefined;
    /**
    * @member {module:model/UsersUserKeys} collaborators
    */
    collaborators = undefined;
    /**
    * @member {module:model/VersionExpandable} _expandable
    */
    _expandable = undefined;
    /**
    * @member {module:model/GenericLinks} _links
    */
    _links = undefined;




}
