/*jshint esversion: 9 */

/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import TaskPageResponse from '../model/TaskPageResponse';

/**
* InlineTasks service.
* @module api/InlineTasksApi
* @version 1.0.0
*/
export default class InlineTasksApi {

    /**
    * Constructs a new InlineTasksApi.
    * @alias module:api/InlineTasksApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesTaskSearchResourceSearchTasksGet operation.
     * @callback module:api/InlineTasksApi~comAtlassianConfluencePluginsRestapiResourcesTaskSearchResourceSearchTasksGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TaskPageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get inline tasks based on search parameters
     * Returns inline tasks based on the search query.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission). Only tasks in contents that the user has permission to view are returned.
     * @param {Object} opts Optional parameters
     * @param {module:api/InlineTasksApi~comAtlassianConfluencePluginsRestapiResourcesTaskSearchResourceSearchTasksGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TaskPageResponse}
     */
    comAtlassianConfluencePluginsRestapiResourcesTaskSearchResourceSearchTasksGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'start': opts.start,
        'limit': opts.limit,
        'spaceKey': opts.spaceKey,
        'pageId': opts.pageId,
        'assignee': opts.assignee,
        'creator': opts.creator,
        'completedUser': opts.completedUser,
        'duedateFrom': opts.duedateFrom,
        'duedateTo': opts.duedateTo,
        'createdateFrom': opts.createdateFrom,
        'createdateTo': opts.createdateTo,
        'completedateFrom': opts.completedateFrom,
        'completedateTo': opts.completedateTo,
        'status': opts.status
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaskPageResponse;

      return this.apiClient.callApi(
        '/api/inlinetasks/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
