/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import LongTaskStatusArray from '../model/LongTaskStatusArray';
import LongTaskStatusWithLinks from '../model/LongTaskStatusWithLinks';

/**
* Longtask service.
* @module api/LongtaskApi
* @version 1.0.0
*/
export default class LongtaskApi {

    /**
    * Constructs a new LongtaskApi. 
    * @alias module:api/LongtaskApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTaskGet operation.
     * @callback module:api/LongtaskApi~comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTaskGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LongTaskStatusWithLinks} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get long-running task
     * Returns information about an active long-running task (e.g. space export), such as how long it has been running and the percentage of the task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission).
     * @param {module:api/LongtaskApi~comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTaskGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LongTaskStatusWithLinks}
     */
    comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTaskGet(id, callback) {
      let postBody = null;

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LongTaskStatusWithLinks;

      return this.apiClient.callApi(
        '/api/longtask/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTasksGet operation.
     * @callback module:api/LongtaskApi~comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTasksGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LongTaskStatusArray} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get long-running tasks
     * Returns information about all active long-running tasks (e.g. space export), such as how long each task has been running and the percentage of each task that has completed.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission).
     * @param {Object} opts Optional parameters
     * @param {module:api/LongtaskApi~comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTasksGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LongTaskStatusArray}
     */
    comAtlassianConfluencePluginsRestapiResourcesLongTaskResourceGetTasksGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LongTaskStatusArray;

      return this.apiClient.callApi(
        '/api/longtask', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
