/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ContentArray from '../model/ContentArray';
import Space from '../model/Space';
import SpaceArray from '../model/SpaceArray';
import SpaceCreate from '../model/SpaceCreate';
import SpacePrivateCreate from '../model/SpacePrivateCreate';
import SpaceProperty from '../model/SpaceProperty';
import SpacePropertyArray from '../model/SpacePropertyArray';
import SpacePropertyCreate from '../model/SpacePropertyCreate';
import SpacePropertyCreateNoKey from '../model/SpacePropertyCreateNoKey';
import SpacePropertyUpdate from '../model/SpacePropertyUpdate';
import SpaceSettings from '../model/SpaceSettings';
import SpaceSettingsUpdate from '../model/SpaceSettingsUpdate';
import SpaceUpdate from '../model/SpaceUpdate';
import SpaceWatchArray from '../model/SpaceWatchArray';
import Theme from '../model/Theme';
import ThemeUpdate from '../model/ThemeUpdate';

/**
* Space service.
* @module api/SpaceApi
* @version 1.0.0
*/
export default class SpaceApi {

    /**
    * Constructs a new SpaceApi. 
    * @alias module:api/SpaceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPost operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceProperty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create space property for key
     * Creates a new space property. This is the same as &#x60;POST /api/space/{spaceKey}/property&#x60; but the key for the property is passed as a path parameter, rather than in the request body.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘Admin’ permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceProperty}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPost(body, spaceKey, key, callback) {
      let postBody = body;

      let pathParams = {
        'spaceKey': spaceKey,
        'key': key
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SpaceProperty;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/property/{key}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPost operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceProperty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create space property
     * Creates a new space property.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘Admin’ permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceProperty}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPost(body, spaceKey, callback) {
      let postBody = body;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SpaceProperty;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/property', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDelete operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete space property
     * Deletes a space property.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘Admin’ permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDelete(spaceKey, key, callback) {
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey,
        'key': key
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/property/{key}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpacePropertyArray} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get space properties
     * Returns all properties for the given space. Space properties are a key-value storage associated with a space.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpacePropertyArray}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGet(spaceKey, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
        'expand': this.apiClient.buildCollectionParam(opts['expand'], 'multi'),
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SpacePropertyArray;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/property', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceProperty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get space property
     * Returns a space property.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceProperty}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGet(spaceKey, key, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey,
        'key': key
      };
      let queryParams = {
        'expand': this.apiClient.buildCollectionParam(opts['expand'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SpaceProperty;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/property/{key}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPut operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceProperty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update space property
     * Updates a space property. Note, you cannot update the key of a space property, only the value.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘Admin’ permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceProperty}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPut(body, spaceKey, key, callback) {
      let postBody = body;

      let pathParams = {
        'spaceKey': spaceKey,
        'key': key
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SpaceProperty;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/property/{key}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePost operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Space} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create private space
     * Creates a new space that is only visible to the creator. This method is the same as the [Create space](#api-space-post) method with permissions set to the current user only. Note, currently you cannot set space labels when creating a space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Create Space(s)&#x27; global permission.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Space}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePost(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Space;

      return this.apiClient.callApi(
        '/api/space/_private', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePost operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Space} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create space
     * Creates a new space. Note, currently you cannot set space labels when creating a space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Create Space(s)&#x27; global permission.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Space}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePost(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Space;

      return this.apiClient.callApi(
        '/api/space', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDelete operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete space
     * Deletes a space. Note, the space will be deleted in a long running task. Therefore, the space may not be deleted yet when this method has returned. Clients should poll the status link that is returned in the response until the task completes.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDelete(spaceKey, callback) {
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContentArray} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get content by type for space
     * Returns all content of a given type, in a space. The returned content is ordered by content ID in ascending order.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space. Note, the returned list will only contain content that the current user has permission to view.
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContentArray}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGet(spaceKey, type, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey,
        'type': type
      };
      let queryParams = {
        'depth': opts['depth'],
        'expand': this.apiClient.buildCollectionParam(opts['expand'], 'multi'),
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ContentArray;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/content/{type}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContentArray} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get content for space
     * Returns all content in a space. The returned content is grouped by type (pages then blogposts), then ordered by content ID in ascending order.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space. Note, the returned list will only contain content that the current user has permission to view.
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContentArray}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGet(spaceKey, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
        'depth': opts['depth'],
        'expand': this.apiClient.buildCollectionParam(opts['expand'], 'multi'),
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ContentArray;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/content', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Space} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get space
     * Returns a space. This includes information like the name, description, and permissions, but not the content in the space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space.
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Space}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGet(spaceKey, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
        'expand': this.apiClient.buildCollectionParam(opts['expand'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Space;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceSettings} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get space settings
     * Returns the settings of a space. Currently only the &#x60;routeOverrideEnabled&#x60; setting can be returned.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;View&#x27; permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceSettings}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGet(spaceKey, callback) {
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SpaceSettings;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/settings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceArray} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get spaces
     * Returns all spaces. The returned spaces are ordered alphabetically in ascending order by space key.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (&#x27;Can use&#x27; global permission). Note, the returned list will only contain spaces that the current user has permission to view.
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceArray}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'spaceKey': this.apiClient.buildCollectionParam(opts['spaceKey'], 'multi'),
        'spaceId': this.apiClient.buildCollectionParam(opts['spaceId'], 'multi'),
        'type': opts['type'],
        'status': opts['status'],
        'label': this.apiClient.buildCollectionParam(opts['label'], 'multi'),
        'favourite': opts['favourite'],
        'favouriteUserKey': opts['favouriteUserKey'],
        'expand': this.apiClient.buildCollectionParam(opts['expand'], 'multi'),
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SpaceArray;

      return this.apiClient.callApi(
        '/api/space', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceWatchArray} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of watchers of a space
     * Returns a list of watchers of a space
     * @param {Object} opts Optional parameters
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceWatchArray}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGet(spaceKey, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
        'start': opts['start'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SpaceWatchArray;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/watch', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePut operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Space} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update space
     * Updates the name, description, or homepage of a space.  -   For security reasons, permissions cannot be updated via the API and must be changed via the user interface instead. -   Currently you cannot set space labels when updating a space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Space}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePut(body, spaceKey, callback) {
      let postBody = body;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Space;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPut operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SpaceSettings} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update space settings
     * Updates the settings for a space. Currently only the &#x60;routeOverrideEnabled&#x60; setting can be updated.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SpaceSettings}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPut(body, spaceKey, callback) {
      let postBody = body;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SpaceSettings;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/settings', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGet operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Theme} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get space theme
     * Returns the theme selected for a space, if one is set. If no space theme is set, this means that the space is inheriting the global look and feel settings.  **[Permissions required](https://confluence.atlassian.com/x/_AozKw)**: ‘View’ permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Theme}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGet(spaceKey, callback) {
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Theme;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/theme', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDelete operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reset space theme
     * Resets the space theme. This means that the space will inherit the global look and feel settings  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDelete(spaceKey, callback) {
      let postBody = null;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/theme', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePut operation.
     * @callback module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Theme} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set space theme
     * Sets the theme for a space. Note, if you want to reset the space theme to the default Confluence theme, use the &#x27;Reset space theme&#x27; method instead of this method.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: &#x27;Admin&#x27; permission for the space.
     * @param {module:api/SpaceApi~comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Theme}
     */
    comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePut(body, spaceKey, callback) {
      let postBody = body;

      let pathParams = {
        'spaceKey': spaceKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oAuthDefinitions'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Theme;

      return this.apiClient.callApi(
        '/api/space/{spaceKey}/theme', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
