/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheConfluenceCloudRestApi);
  }
}(this, function(expect, TheConfluenceCloudRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheConfluenceCloudRestApi.BlueprintTemplate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BlueprintTemplate', function() {
    it('should create an instance of BlueprintTemplate', function() {
      // uncomment below and update the code to test BlueprintTemplate
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be.a(TheConfluenceCloudRestApi.BlueprintTemplate);
    });

    it('should have the property templateId (base name: "templateId")', function() {
      // uncomment below and update the code to test the property templateId
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property originalTemplate (base name: "originalTemplate")', function() {
      // uncomment below and update the code to test the property originalTemplate
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property referencingBlueprint (base name: "referencingBlueprint")', function() {
      // uncomment below and update the code to test the property referencingBlueprint
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property labels (base name: "labels")', function() {
      // uncomment below and update the code to test the property labels
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property templateType (base name: "templateType")', function() {
      // uncomment below and update the code to test the property templateType
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property expandable (base name: "_expandable")', function() {
      // uncomment below and update the code to test the property expandable
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "_links")', function() {
      // uncomment below and update the code to test the property links
      //var instane = new TheConfluenceCloudRestApi.BlueprintTemplate();
      //expect(instance).to.be();
    });

  });

}));
