/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheConfluenceCloudRestApi);
  }
}(this, function(expect, TheConfluenceCloudRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheConfluenceCloudRestApi.ContentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContentApi', function() {
    describe('comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateAttachmentsPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateAttachmentsPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateAttachmentsPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateAttachmentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateOrUpdateAttachmentsPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateOrUpdateAttachmentsPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateOrUpdateAttachmentsPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceCreateOrUpdateAttachmentsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceGetAttachmentsGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceGetAttachmentsGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceGetAttachmentsGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceGetAttachmentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentDataPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentDataPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentDataPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentDataPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentPropertiesPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentPropertiesPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentPropertiesPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesAttachmentResourceUpdateAttachmentPropertiesPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenByTypeGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenByTypeGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenByTypeGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenByTypeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentChildrenGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentCommentsGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentCommentsGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentCommentsGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesChildContentResourceGetContentCommentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishLegacyDraftPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishLegacyDraftPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishLegacyDraftPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishLegacyDraftPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishSharedDraftPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishSharedDraftPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishSharedDraftPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentBlueprintResourcePublishSharedDraftPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceAddLabelsToContentPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceAddLabelsToContentPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceAddLabelsToContentPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceAddLabelsToContentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceGetLabelsForContentGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceGetLabelsForContentGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceGetLabelsForContentGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceGetLabelsForContentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentUsingQueryParameterDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentUsingQueryParameterDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentUsingQueryParameterDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentLabelsResourceRemoveLabelFromContentUsingQueryParameterDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForPageGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForPageGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForPageGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForPageGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForSpaceGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForSpaceGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForSpaceGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentNotificationsResourceGetWatchesForSpaceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyForKeyPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyForKeyPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyForKeyPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyForKeyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceCreateContentPropertyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceDeleteContentPropertyDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceDeleteContentPropertyDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceDeleteContentPropertyDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceDeleteContentPropertyDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertiesGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertiesGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertiesGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertiesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertyGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertyGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertyGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceGetContentPropertyGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceUpdateContentPropertyPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceUpdateContentPropertyPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceUpdateContentPropertyPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentPropertyResourceUpdateContentPropertyPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceCreateContentPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceCreateContentPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceCreateContentPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceCreateContentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceDeleteContentDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceDeleteContentDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceDeleteContentDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceDeleteContentDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentByIdGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentByIdGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentByIdGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceGetContentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceGetHistoryForContentGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceGetHistoryForContentGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceGetHistoryForContentGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceGetHistoryForContentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceGetMacroBodyByMacroIdGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceGetMacroBodyByMacroIdGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceGetMacroBodyByMacroIdGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceGetMacroBodyByMacroIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceSearchContentByCQLGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceSearchContentByCQLGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceSearchContentByCQLGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceSearchContentByCQLGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentResourceUpdateContentPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentResourceUpdateContentPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentResourceUpdateContentPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentResourceUpdateContentPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddGroupToContentRestrictionPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddGroupToContentRestrictionPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddGroupToContentRestrictionPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddGroupToContentRestrictionPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddRestrictionsPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddRestrictionsPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddRestrictionsPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddRestrictionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddUserToContentRestrictionPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddUserToContentRestrictionPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddUserToContentRestrictionPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceAddUserToContentRestrictionPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceDeleteRestrictionsDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceDeleteRestrictionsDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceDeleteRestrictionsDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceDeleteRestrictionsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForGroupGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForGroupGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForGroupGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForGroupGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForUserGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForUserGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForUserGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetContentRestrictionStatusForUserGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsByOperationGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsByOperationGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsByOperationGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsByOperationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsForOperationGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsForOperationGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsForOperationGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsForOperationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceGetRestrictionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveGroupFromContentRestrictionDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveGroupFromContentRestrictionDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveGroupFromContentRestrictionDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveGroupFromContentRestrictionDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveUserFromContentRestrictionDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveUserFromContentRestrictionDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveUserFromContentRestrictionDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceRemoveUserFromContentRestrictionDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceUpdateRestrictionsPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceUpdateRestrictionsPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceUpdateRestrictionsPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentRestrictionResourceUpdateRestrictionsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceDeleteContentVersionDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceDeleteContentVersionDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceDeleteContentVersionDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceDeleteContentVersionDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionsGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionsGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionsGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceGetContentVersionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceRestoreContentVersionPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceRestoreContentVersionPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceRestoreContentVersionPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesContentVersionResourceRestoreContentVersionPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceDescendantsOfTypeGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceDescendantsOfTypeGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceDescendantsOfTypeGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceDescendantsOfTypeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceGetContentDescendantsGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceGetContentDescendantsGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceGetContentDescendantsGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesDescendantContentResourceGetContentDescendantsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesPageHierarchyResourceCopyPageHierarchyPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesPageHierarchyResourceCopyPageHierarchyPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesPageHierarchyResourceCopyPageHierarchyPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesPageHierarchyResourceCopyPageHierarchyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
