/**
 * The Confluence Cloud REST API
 * This document describes the REST API and resources provided by Confluence. The REST APIs are for developers who want to integrate Confluence into their application and for administrators who want to script interactions with the Confluence server.Confluence's REST APIs provide access to resources (data entities) via URI paths. To use a REST API, your application will make an HTTP request and parse the response. The response format is JSON. Your methods will be the standard HTTP methods like GET, PUT, POST and DELETE. Because the REST API is based on open standards, you can use any web development language to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheConfluenceCloudRestApi);
  }
}(this, function(expect, TheConfluenceCloudRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheConfluenceCloudRestApi.SpaceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SpaceApi', function() {
    describe('comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyForKeyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPost
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceCreateSpacePropertyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceDeleteSpacePropertyDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertiesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceGetSpacePropertyGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpacePropertyResourceUpdateSpacePropertyPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePost
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreatePrivateSpacePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePost', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePost successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePost
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceCreateSpacePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceDeleteSpaceDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentByTypeForSpaceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetContentForSpaceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpaceSettingsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetSpacesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceGetWatchersForSpaceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePut
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpacePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPut
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceResourceUpdateSpaceSettingsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGet', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGet successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGet
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceGetSpaceThemeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDelete', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDelete successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDelete
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceResetSpaceThemeDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePut', function() {
      it('should call comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePut successfully', function(done) {
        //uncomment below and update the code to test comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePut
        //instance.comAtlassianConfluencePluginsRestapiResourcesSpaceThemeResourceSetSpaceThemePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
